### ISSUE TITLE
c flags and dependencies

### ISSUE THREAD

**Issue by aburrell** [asreimer/lmfit2#1]
I'm having trouble getting the C code to compile.  Problems I've had:

- Bstatic/dynamic flag unknown (-static/dynamic work)
- The library for "-lz" isn't found.  Which library is this referencing for you?  I didn't see anything about this in the README.

**Comment by asreimer** [comment]
Until I update the readme: https://stackoverflow.com/questions/3373995/usr-bin-ld-cannot-find-lz
Also, I don't know what system you are on when you got these errors.

The Bstatic/dynamic flag sounds like a a Mac OSX issue (or as I like to call them: a personal problem, just kidding!): Maybe this will help? https://groups.google.com/forum/#!topic/gnu.gcc.help/RDiauUNe1bE

Did you install RST or RSTLite? I think the zlib is a requirement for those to install properly.

I think I can spend some time working on this next week. It happens to line up with work actually!

**Comment by aburrell** [comment]
Heh,

So.  I spent a bit more time working on this.  I found some typos in your makefile (INLUDE instead of INCLUDE; multiple definitions of the same thing).  I also managed to add a OS detection bit for flag declaration.  So it’d at least be set up for mac and linux (not windows, would need command-line level definition there).

But, I ended up with this issue within make_lmfit2:

ld: library not found for -lSystem

I found this particularly confusing because there’s no reference to a library named System?

Also, this happens even if I only make changes for the -lz, -static, and -dynamic flags.

Cheers,
Angeline

**Comment by aburrell** [comment]
Other bit of info:  Have rst 4.0 installed.  Worked out the OSX installation for that pre-SuperDARN workshop.

**Comment by asreimer** [comment]
The includes typo doesn't affect installation of this package. The "inludes" found later are not actually needed.

The zlib requirement is a requirement to installing RSTLite. I've added a line to the README about making sure you have zlib dev installed on your machine. I've also added a subsection to guide users to make sure that they source the .profile.bash file in the RSTLite.
