### ISSUE TITLE
Adding lmfit2 to the SuperDARN RST

### ISSUE THREAD

**Issue by ecbland** [asreimer/lmfit2#12]
Hei @asreimer! 

I'm reaching out because there have been several requests to add this library to the [RST](https://github.com/SuperDARN/rst). We can take care of the implementation, but I just wanted to touch base first. Are you happy for us to copy the code? And do you recommend that we copy the `develop` branch (which seems to include some bug fixes)? RST and `lmfit2` are both licensed under the GPLv3 so there will be no problems there. 

Thanks!
Emma

**Comment by asreimer** [comment]
Hey @ecbland, thanks for reaching out. I'm happy to see interest in this being integrated into RST.

Looks like https://github.com/SuperDARN/rst/pull/514 is done now, but I just wanted to confirm that the latest commit was in the develop branch to add analytic jacobians to speed up the underlying Levenburg-Marquardt algorithm.
