### ISSUE TITLE
Issue creating the lmfit2 file with the python version 

### ISSUE THREAD

**Issue by samuelwharton** [asreimer/lmfit2#4]
Hi Ashton, 
I've been trying to run your lmfit2 code and I've been having some problems. I'm using python 2.7.13 and numpy 1.11.2. I'm trying to create the lmfit2 file from the rawacf file (20120614.0001.00.sas.rawacf) for the saskatoon data from Reimer et al. (2018) paper and keep I getting the following error:

    Traceback (most recent call last):
      File "lmfit2.py", line 648, in <module>
        fitted_records = [p.get() for p in temp]
      File "/cm/shared/apps/python/gcc/2.7.13/lib/python2.7/multiprocessing/pool.py", line 567, in get
        raise self._value
    TypeError: only integer arrays with one element can be converted to an index

Any help would be brilliant!
Thanks, 
Samuel

**Comment by asreimer** [comment]
Hey @samuelwharton,

I was able to reproduce your problem by running:

    cd lmfit2/python
    python
    import lmfit2
    lmfit2.main('20120614.0401.00.sas.rawacf','20120614.0401.00.sas.lmfit2')

I received the following output:

    It took 66.655306 seconds to fit one beam.
    It took 58.722186 seconds to fit one beam.
    It took 60.549947 seconds to fit one beam.
    It took 60.732639 seconds to fit one beam.
    It took 61.9701 seconds to fit one beam.
    It took 59.734899 seconds to fit one beam.
    It took 55.637972 seconds to fit one beam.
    It took 62.582238 seconds to fit one beam.
    It took 67.03054 seconds to fit one beam.
    It took 78.828935 seconds to fit one beam.
    It took 80.917881 seconds to fit one beam.
    It took 70.545094 seconds to fit one beam.
    It took 74.720414 seconds to fit one beam.
    SOMETHING WEIRD IS HAPPENING
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-4-ec45ea919bda> in <module>()
    ----> 1 lmfit2.main(filename,output)

    /home/ashtonsethreimer/lmfit2/python/lmfit2.py in main(input_filename, output_filename)
        615     #next iterate through all records and fit them
        616     for record in records:
    --> 617         fit_record = lmfit2(record)
        618         if isinstance(fit_record,dict):
        619             fitted_records.append(fit_record)

    /home/ashtonsethreimer/lmfit2/python/lmfit2.py in lmfit2(record)
        523             ind = ind[0]
        524 
    --> 525         pwr_fit = outs2[ind].params['power'].value
        526         wid_fit = outs2[ind].params['width'].value
        527         vel_fit = outs2[ind].params['velocity'].value

    TypeError: only integer scalar arrays can be converted to a scalar index

It stems from not handling the case where `ind = np.where(chi2 == np.min(chi2))[0]` doesn't return an `ind` with a size of 1. Not sure exactly what is happening here, so I'll need time to debug it.

In the mean time, can you run some unit tests to make sure there isn't any other bug happening? Here's what you can do to run the unit test:

    git clone https://github.com/asreimer/lmfit2.git
    cd lmfit2/python
    git fetch origin feature-testing:feature-testing
    git checkout feature-testing
    python tests/test.py

And here's the output that I get:

    [ashtonsethreimer@x250 python]$ python tests/test.py 
    Running multiprocessing test on 2 threads.
    It took 63.766315 seconds to fit one beam.
    It took 70.778986 seconds to fit one beam.
    It took 66.216149 seconds to fit one beam.
    It took 65.323967 seconds to fit one beam.
    It took 61.550965 seconds to fit one beam.
    .Running single processing test.
    It took 65.188284 seconds to fit one beam.
    It took 58.729126 seconds to fit one beam.
    It took 60.90118 seconds to fit one beam.
    It took 58.71785 seconds to fit one beam.
    It took 60.137074 seconds to fit one beam.
    .
    ----------------------------------------------------------------------
    Ran 2 tests in 496.598s

    OK


This will run a unit test that I just finished creating. It takes ~10 minutes to run on my slow laptop.

**Comment by samuelwharton** [comment]
I have just run the test you asked for on my computer and I got the same output as you, with similar times. Here is that output:

Running multiprocessing test on 2 threads.
It took 60.834016 seconds to fit one beam.
It took 73.061166 seconds to fit one beam.
It took 64.292326 seconds to fit one beam.
It took 58.560144 seconds to fit one beam.
It took 63.807257 seconds to fit one beam.
.Running single processing test.
It took 64.801075 seconds to fit one beam.
It took 56.382321 seconds to fit one beam.
It took 57.435413 seconds to fit one beam.
It took 58.563872 seconds to fit one beam.
It took 57.889628 seconds to fit one beam.
.
----------------------------------------------------------------------
Ran 2 tests in 487.765s

OK

**Comment by asreimer** [comment]
Alright. The python code has trouble with fitting the 14th record in the file: `20120614.0401.00.sas.rawacf`. The records are 28969 bytes each. So to make debugging easier, I created a "trimmed" file that starts at the 14th record and is only 5 records long. I did this using:

    dd if=20120614.0401.00.sas.rawacf of=temp.rawacf ibs=28969 skip=13
    head -c 144845 temp.rawacf > trimmed_20120614.0401.00.sas.rawacf

And then I ran the fitting on the "trimmed" file:

    ipython
    import lmfit2
    lmfit2.main('trimmed_20120614.0401.00.sas.rawacf','output.lmfit2')
    SOMETHING WEIRD IS HAPPENING

Adding some print statements, I found that it crashes on range gate 5 (zero based indexing). It was crashing due to the following logic:

    ind = np.where(chi2 == np.min(chi2))[0]
    
    if (ind.size != 1):
        print "SOMETHING WEIRD IS HAPPENING"
    else:
        ind = ind[0]

Since the velocity dimension of the chi-squared space has several local minimum (see [my paper](http://onlinelibrary.wiley.com/doi/10.1002/2017RS006450/abstract), figure 4), and the Levenburg-Marquardt algorithm can "get stuck" in a local minimum depending on the initial guess used, we need to make several initial guesses for the fitted velocity and then compare the chi-squared of the fit for each initial guess. The numpy where statement can return multiple indicies if several initial velocity guesses produce the same chi-square values (fall in to the same local minimum!). So that's not weird! That's expected!

To fix this, I removed the if statement entirely and modified the where statement to be:

    ind = np.where(chi2 == np.min(chi2))[0][0]

So now the python lmfit2 code should "just work".

@samuelwharton, can you please try running the following using this trimmed rawacf file:
[trimmed_20120614.0401.00.sas.zip](https://github.com/asreimer/lmfit2/files/1941525/trimmed_20120614.0401.00.sas.zip)

    python
    import lmfit2
    lmfit2.main('trimmed_20120614.0401.00.sas.rawacf','output.lmfit2')

Please run this code from the feature-testing branch. If it works for you, I'll merge everything in to the master branch. Here's the output I got for comparison:

    It took 71.317585 seconds to fit one beam.
    It took 77.279879 seconds to fit one beam.
    It took 64.378154 seconds to fit one beam.
    It took 94.640895 seconds to fit one beam.
    It took 72.205424 seconds to fit one beam.

**Comment by samuelwharton** [comment]
Ok, so I tried to run it on the trimmed rawacf file you posted with the changes to the lmfit2 file you made above and I got the below error. Not sure what has happened here. I ran it from the same place as the previous test you sent me. Below that I have posted the modified section of the lmfit2 file so you can see exactly what I've done. Let me know if you need anything else.

>>> import lmfit2
>>> lmfit2.main('trimmed_20120614.0401.00.sas.rawacf','output.lmfit2')
SOMETHING WEIRD IS HAPPENING
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lmfit2.py", line 619, in main
    fit_record = lmfit2(record)
  File "lmfit2.py", line 527, in lmfit2
    pwr_fit = outs2[ind].params['power'].value
TypeError: only integer arrays with one element can be converted to an index


479        chi2 = np.array([out.chisqr for out in outs])
480        #ind = np.where(chi2 == np.min(chi2))[0]
481
482        #if (ind.size != 1):
483        #    print "SOMETHING WEIRD IS HAPPENING"
484        #else:
485        #    ind = ind[0]
486
487	      ind = np.where(chi2 == np.min(chi2))[0][0]
488
489        pwr_fit = outs[ind].params['power'].value
490        wid_fit = outs[ind].params['width'].value
491        vel_fit = outs[ind].params['velocity'].value

**Comment by asreimer** [comment]
Hey @samuelwharton 

Likely, you did not modify the whole file. There are 2 places where this if statement occurs.

Please don't try to modify the file yourself. Instead, perform a pull from the `feature-testing` branch using git. That's one of the great things about using git, we can make sure we are all using the same code. Make sure you are in the `feature-testing` branch. Then run:

    git pull origin feature-testing

Then you can try processing the trimmed file.

**Comment by samuelwharton** [comment]
Okay, so I had to fix my end to remove local changes before I could run your bit. I did this using:
git reset --hard
Then I was able to use the pull command and repeat the running of the lmfit2 code. Happily, it worked and this was my output:

>>> import lmfit2
>>> lmfit2.main('trimmed_20120614.0401.00.sas.rawacf','output.lmfit2')
It took 77.757891 seconds to fit one beam.
It took 74.467634 seconds to fit one beam.
It took 57.028363 seconds to fit one beam.
It took 89.656011 seconds to fit one beam.
It took 71.847713 seconds to fit one beam.

**Comment by asreimer** [comment]
Perfect!

Let me know if you encounter any other issues. It seems that the python code "just works" now though.

In the next 1-2 weeks, I'll be fixing up the C code in preparation for the workshop. When that's done and the installation process is a bit simpler, I'll let you know. As you can imagine, the C code is much faster than the python code.

**Comment by samuelwharton** [comment]
Thanks for your help on this. I'm going to try running it on lots of different files. I'm currently running it on '20120614.0001.00.sas.rawacf' and I have got a runtime warning but it hasn't stopped it working:

It took 71.65645 seconds to fit one beam.
It took 62.592436 seconds to fit one beam.
It took 53.498988 seconds to fit one beam.
It took 75.919397 seconds to fit one beam.
It took 72.675484 seconds to fit one beam.
It took 71.851255 seconds to fit one beam.
It took 79.048167 seconds to fit one beam.
It took 69.042503 seconds to fit one beam.
It took 75.726079 seconds to fit one beam.
lmfit2.py:546: RuntimeWarning: invalid value encountered in log10
  p_l.append(10.0*np.log10(fitted_power[i]/noise))
lmfit2.py:547: RuntimeWarning: invalid value encountered in log10
  p_l_e.append(10.0*np.log10((fitted_power_e[i]+fitted_power[i])/noise)-10.0*np.log10(fitted_power[i]/noise))
It took 65.601488 seconds to fit one beam.
It took 64.464585 seconds to fit one beam.

Don't know if this is a major problem. Also, I'll send you an email about something else too. Thanks

**Comment by samuelwharton** [comment]
Hi Ashton, 

This problem with invalid values is still preventing the code from running. Just tried running it again on '20120614.0001.00.sas.rawacf' and I get this error. It clearly doesn't like the nan values. 

/home/s/sjw136/Python2/testlmfit2/lmfit2/python/lmfit2.py:546: RuntimeWarning: invalid value encountered in log10
  p_l.append(10.0*np.log10(fitted_power[i]/noise))
/home/s/sjw136/Python2/testlmfit2/lmfit2/python/lmfit2.py:547: RuntimeWarning: invalid value encountered in log10
  p_l_e.append(10.0*np.log10((fitted_power_e[i]+fitted_power[i])/noise)-10.0*np.log10(fitted_power[i]/noise))
/home/s/sjw136/Python2/testlmfit2/lmfit2/python/lmfit2.py:198: RuntimeWarning: invalid value encountered in sqrt
  return (power+noise+clutter)*np.sqrt((1-rho**2)/2. + rho_c**2)/np.sqrt(nave)
Traceback (most recent call last):
  File "/home/s/sjw136/Python2/testlmfit2/lmfit2/python/run_lmfit2.py", line 22, in <module>
    lmfit2.main(input_name, output_name) 
  File "/home/s/sjw136/Python2/testlmfit2/lmfit2/python/lmfit2.py", line 607, in main
    fit_record = lmfit2(record)
  File "/home/s/sjw136/Python2/testlmfit2/lmfit2/python/lmfit2.py", line 510, in lmfit2
    outs2.append(minner.minimize())
  File "/home/s/sjw136/.local/lib/python2.7/site-packages/lmfit/minimizer.py", line 1649, in minimize
    return function(**kwargs)
  File "/home/s/sjw136/.local/lib/python2.7/site-packages/lmfit/minimizer.py", line 1302, in leastsq
    lsout = scipy_leastsq(self.__residual, vars, **lskws)
  File "/cm/shared/apps/python/gcc/2.7.13/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 377, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
  File "/cm/shared/apps/python/gcc/2.7.13/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 26, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/home/s/sjw136/.local/lib/python2.7/site-packages/lmfit/minimizer.py", line 489, in __residual
    out = _nan_policy(out, nan_policy=self.nan_policy)
  File "/home/s/sjw136/.local/lib/python2.7/site-packages/lmfit/minimizer.py", line 1837, in _nan_policy
    raise ValueError("The input contains nan values")
ValueError: The input contains nan values

Any help would be great, hopefully this is the last issue!!!

**Comment by asreimer** [comment]
Investigating now. This is happening probably because the variance calculation is returning a NaN for some reason. Looks like the `lmfit` python package doesn't handle NaNs nicely.

I'm digging in to this now, but do you happen to remember where approximately in the '20120614.0001.00.sas.rawacf' file this happens? At the beginning? Half way through? Near the end?

**Comment by samuelwharton** [comment]
I've attached the error file I got back for you

-------------------------------------------------------------------------------------------------------------------------------------------
Samuel Wharton
PhD Student

Room F65
Radio and Space Plasma Physics
Department of Physics and Astronomy
University of Leicester
Leicester, LE1 7RH

**Comment by samuelwharton** [comment]
And it was the 4th beam

-------------------------------------------------------------------------------------------------------------------------------------------
Samuel Wharton
PhD Student

Room F65
Radio and Space Plasma Physics
Department of Physics and Astronomy
University of Leicester
Leicester, LE1 7RH

**Comment by samuelwharton** [comment]
Here the output file that tells you where it got too. It repeats itself twice because I ran it twice ☺

-------------------------------------------------------------------------------------------------------------------------------------------
Samuel Wharton
PhD Student

Room F65
Radio and Space Plasma Physics
Department of Physics and Astronomy
University of Leicester
Leicester, LE1 7RH

**Comment by asreimer** [comment]
The file is now '20120614.1601.00.sas.rawacf' instead of '20120614.0001.00.sas.rawacf'? Or it happened on both? :)

**Comment by samuelwharton** [comment]
I set it to run on all files on 20120614 but for some reason, it likes to tackle them in random order. There should be 12 files in total

-------------------------------------------------------------------------------------------------------------------------------------------
Samuel Wharton
PhD Student

Room F65
Radio and Space Plasma Physics
Department of Physics and Astronomy
University of Leicester
Leicester, LE1 7RH

**Comment by asreimer** [comment]
Ok! My code finally crashed while processing  '20120614.1601.00.sas.rawacf'. It crashed on the 4th record (record 3 in zero based indexing) on range gate 73 in zero based indexing. Now I can start working on why.

**Comment by asreimer** [comment]
Alright, it's fixed.

The problem was in the fitted parameter limits. I was allowing the fitted power to come out as negative, which is nonsensical, especially when it is used to estimate the variance for the second round of fitting. I added some verbosity to the fitting process too so now it tells you which record, beam, and gate it is fitting.

I also found a bug in how rho_re and rho_im were being calculated. This bug is not present in the C code and was unique to the python code; a result of the python code not being tested as well as the C code (which has successfully fit 8 years of Saskatoon SuperDARN radar data).

@samuelwharton can you pull down the `feature-testing` branch and try to fit 20120614.1601.00.sas.rawacf again? It should work now :)

**Comment by asreimer** [comment]
I was able to run the code on the whole file (just finished today), so I think this issue is fixed.

**Comment by samuelwharton** [comment]
How long did it take you to run it? Was that just a single file? It’s working for me but I didn’t ask for enough processing time so I’m doing it again. Would you be able to advise me on how to run the C version?

-------------------------------------------------------------------------------------------------------------------------------------------
Samuel Wharton
PhD Student

Room F65
Radio and Space Plasma Physics
Department of Physics and Astronomy
University of Leicester
Leicester, LE1 7RH

**Comment by asreimer** [comment]
@samuelwharton it took several days. I don't know how long precisely, but roughly 2 days based on my comments in this thread.
