### ISSUE TITLE
Migrate to dependency on SuperDARN/rst

### ISSUE THREAD

**Issue by asreimer** [asreimer/lmfit2#5]
Currently C code depends on deprecated VTRST3.5 or RSTLite. Should be migrated to new supported SuperDARN/rst.

**Comment by egthomas** [comment]
A minor recommendation when migrating the C code to the newer 4.X versions of the RST would be to name the library and binary directories `lmfit2.1.0` and `make_lmfit2.1.0` respectively.  Weird things happen during compilation if you drop the major or minor version number from the directory name.

I would like to remove the version numbers from the directory names entirely and instead store the values somewhere else like a file, but that will wipe out all of the git history to date.  Of course the longer we wait the more painful it will be; right now we're stuck in somewhat of a purgatory where we're modifying the libraries/binaries but can't easily update their version numbers.

**Comment by asreimer** [comment]
@egthomas Thanks! That is good to know for when I make a pull request to the rst library.

In regards to the purgatory, and you probably are doing this, but you can get rst to a solid point, then make a hard change that hurts the history. If the codebase is pretty much bug free, then the history doesn't matter as much. Also, it's not like the history is gone, you just have to dig a bit harder for it :)

**Comment by egthomas** [comment]
A bug free RST?  That would be the day...

**Comment by asreimer** [comment]
It doesn't have to be bug free. Just like a PhD thesis, it doesn't have to be perfect, it just needs to get done. Pick a release version and decide that after that the next thing that will happen is refactoring. We did this for davitpy, which is a buggier codebase than the current rst.

**Comment by asreimer** [comment]
Late night testing note:

Nothing needs to be changed for the C code to compile. All you need to do is install rst properly and the C code here will compile happily.

Need to update installation instructions and dependency notes.

**Comment by asreimer** [comment]
With #8, installation instructions include information on how to compile lmfit2 against RST.
